#!/usr/bin/with-contenv bash
set -e

cd /mosquitto || exit 1; # must exist

MOSQUITTO_CONFDIR="${MOSQUITTO_CONFDIR:-/mosquitto/config}";
MOSQUITTO_ARGS="${MOSQUITTO_ARGS:- -c ${MOSQUITTO_CONFDIR}/mosquitto.conf}";

s6-setuidgid ${S6_USER:-alpine} \
exec \
    mosquitto \
    ${MOSQUITTO_ARGS} \
    ;
